# Generated by Django 4.2 on 2023-04-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes_list", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name="UsersSite",
        ),
        migrations.RemoveField(
            model_name="quotes",
            name="tags",
        ),
        migrations.AddField(
            model_name="quotes",
            name="tags",
            field=models.ManyToManyField(to="quotes_list.tag"),
        ),
    ]
