# Generated by Django 4.2 on 2023-04-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes_list", "0002_tag_delete_userssite_remove_quotes_tags_quotes_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authors",
            name="fullname",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
