# Generated by Django 4.2 on 2023-04-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes_list", "0003_alter_authors_fullname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authors",
            name="description",
            field=models.CharField(max_length=20000),
        ),
        migrations.AlterField(
            model_name="quotes",
            name="quote",
            field=models.CharField(max_length=20000),
        ),
    ]
