# Generated by Django 4.2 on 2023-04-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UsersSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=200)),
                ("login", models.CharField(max_length=200)),
                (
                    "avatar",
                    models.ImageField(
                        default="default_avatar.png", upload_to="profile_images"
                    ),
                ),
            ],
        ),
    ]
